### ISSUE TITLE
How to get opt.txt in Comp_v6_KLD005 for customized training data?

### ISSUE THREAD

**Issue by hdjsjyl** [EricGuo5513/momask-codes#23]
Hi Author,
    How to get opt.txt in Comp_v6_KLD005 for customized training data? Since it is needed for both training and eval. Thanks

**Comment by Murrol** [comment]
I recommend checking the opt.txt file and manually modifying it according to your requirements. Specifically, for customized data, since you don't have a neural evaluator, you may need to design and implement one. The evaluator is essentially a cross-modality feature encoder. You can refer to the [T2M](https://github.com/EricGuo5513/text-to-motion) repository for more information. Please note that I cannot code or debug for you.

Simplest solution:
Remove all the code related to the evaluator or causing bugs, and you will have a runnable training script.
