### ISSUE TITLE
Can this model replace the visualization/data/template.bvh file with other character skeleton .bvh file without the need for retraining?

### ISSUE THREAD

**Issue by shisgbdus** [EricGuo5513/momask-codes#36]

**Comment by Murrol** [comment]
Sorry for the late response. You can get a motion in the human-like key-point representation from our model. Converting this representation into bvh file, especially with other skeleton, might involve additional retargeting process. Using other character with the same skeleton topology might work. Otherwise, you might need to modify the retargeting method or retrain the model.
